#!/bin/bash

echo "----------------欢迎使用Surge脚本工具--------------------"
echo "选项列表："
echo "0. 更新这个脚本（测试）"
echo "1. docker- 一键安装Surge-v4"
echo "2. docker- 一键安装Surge-v4 shadow-tls v3"
echo "3. 一键安装Hy2"
echo "4. 无docker 一键安装Senll"
echo "5. 无docker 一键卸载Senll"
echo "6. 一键卸载docker snell（会卸载docker）"
read -p "请选择一个操作（0、1、2、3、4、5或6）: " user_choice

case $user_choice in
0)
    echo "正在更新脚本..."
    TEMP_SCRIPT="temp_update_script.sh"
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/mian_surge_v4 -O "$TEMP_SCRIPT"
    if [ $? -eq 0 ]; then
        chmod +x "$TEMP_SCRIPT"
        mv "$TEMP_SCRIPT" "$(basename $0)"
        echo "脚本已更新。正在重新执行脚本..."
        exec ./"$(basename $0)"
    else
        echo "更新失败，请检查网络连接或URL是否正确。"
        rm -f "$TEMP_SCRIPT"  # 确保删除临时文件
    fi
    exit 0
    ;;

1)
    echo "正在安装Surge-v4..."
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/snellv4-docker -O snellv4-docker.sh
    chmod +x snellv4-docker.sh
    ./snellv4-docker.sh
    ;;
2)
    echo "正在安装Surge-v4 shadow-tls v3..."
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/senll-tls.sh -O senll-tls.sh
    chmod +x senll-tls.sh
    ./senll-tls.sh
    ;;
3)
    echo "正在安装Hy2..."
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/hy2.sh -O hy2.sh
    chmod +x hy2.sh
    ./hy2.sh
    ;;
4)
    echo "正在安装Senll-无docker版本..."
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/snell-none-tls.sh -O snell-none-tls.sh
    chmod +x snell-none-tls.sh
    ./snell-none-tls.sh
    ;;
5)
    echo "正在卸载Senll-无docker版本..."
    wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/uninstall_snell-none-tls.sh -O uninstall_snell-none-tls.sh
    chmod +x uninstall_snell-none-tls.sh
    ./uninstall_snell-none-tls.sh
    ;;
6)
    echo "警告：你将要卸载Surge-v4 shadow-tls v3，这会移除整个容器。"
    read -p "确定要继续吗？(yes/no): " confirm
    if [[ $confirm == "yes" ]]; then
        echo "正在卸载..."
        wget https://raw.githubusercontent.com/Jaydooooooo/Suege-/main/uninstll_surge_with_tls -O uninstll_surge_with_tls.sh
        chmod +x uninstll_surge_with_tls.sh
        ./uninstll_surge_with_tls.sh
    else
        echo "卸载操作已取消。"
    fi
    ;;
*)
    echo "无效的输入，脚本退出。"
    exit 1
    ;;
esac
