#!/bin/bash

# 停止并删除Docker容器
echo "正在停止并删除Docker容器..."
cd /root/snelldocker
docker compose down >/dev/null 2>&1
echo "Docker容器已停止并删除。"

# 删除安装和配置文件
echo "正在删除安装和配置文件..."
rm -rf /root/snelldocker

# 检查Docker是否安装，如果安装则卸载
if [ -x "$(command -v docker)" ]; then
    echo "正在卸载Docker..."
    apt-get remove --purge -y docker docker-engine docker.io containerd runc >/dev/null 2>&1
    apt-get autoremove -y >/dev/null 2>&1
    echo "Docker已卸载。"
else
    echo "Docker未安装，跳过卸载步骤。"
fi

# 检查Docker Compose插件是否安装，如果安装则卸载
if [ -x "$(command -v docker-compose)" ]; then
    echo "正在卸载Docker Compose插件..."
    apt-get remove --purge -y docker-compose-plugin >/dev/null 2>&1
    apt-get autoremove -y >/dev/null 2>&1
    echo "Docker Compose插件已卸载。"
else
    echo "Docker Compose插件未安装，跳过卸载步骤。"
fi

# 清理未使用的Docker资源
docker system prune -a -f >/dev/null 2>&1

# 完成
echo "卸载完成。"
